apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pinger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pinger
    spec:
      containers:
      - name: pinger
        image: library/pinger:latest
        imagePullPolicy: Never # required for k3d imported images

---

apiVersion: v1
kind: Service
metadata:
  name: pinger
spec:
  selector:
    app.kubernetes.io/name: pinger
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

